import "../styles/globals.css";

import { ChakraProvider, extendTheme, HStack, Link } from "@chakra-ui/react";
import { Provider } from "next-auth/client";
import { Provider as JotaiProvider } from "jotai";
import Head from "next/head";
import NextLink from "next/link";

const theme = extendTheme({});

function MyApp({ Component, pageProps }) {
  return (
    <JotaiProvider>
      <ChakraProvider theme={theme}>
        <Provider session={pageProps.session}>
          <Head>
            <title>Expense Tracker</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="style"></link>
          </Head>
          <HStack
            justify="space-between"
            borderBottom="1px solid blue.900"
            h="4rem"
            padding="1rem"
            marginBottom="1rem"
            backgroundColor="blue.600"
          >
            <NextLink href="/">
              <Link
                _hover={{
                  textDecor: "none",
                  color: "blue.50",
                }}
                color="white"
                fontSize="2rem"
                className="logo"
              >
                Expense Tracker
              </Link>
            </NextLink>
            <HStack spacing="2rem">
              <NextLink href="/add-income-and-expense">
                <Link
                  color="white"
                  _hover={{
                    textDecor: "none",
                    color: "blue.50",
                  }}
                >
                  Edit Budget
                </Link>
              </NextLink>
              <NextLink href="/auth">
                <Link
                  color="white"
                  _hover={{
                    textDecor: "none",
                    color: "blue.50",
                  }}
                >
                  Login/Logout
                </Link>
              </NextLink>
            </HStack>
          </HStack>
          <Component {...pageProps} />
        </Provider>
      </ChakraProvider>
    </JotaiProvider>
  );
}

export default MyApp;
