import Head from "next/head";
import styles from "../styles/Home.module.css";
import {
  HStack,
  StatGroup,
  Stat,
  StatLabel,
  StatNumber,
  Table,
  Thead,
  Tbody,
  Th,
  Tr,
  // Td,
} from "@chakra-ui/react";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>React NextJs Budget App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HStack justify="space-around">
          <section>
            <p>Expenses</p>
            <Table>
              <Thead>
                <Tr>
                  <Th>Name</Th>
                  <Th>Frequency</Th>
                  <Th>Amount</Th>
                  <Th>Annual Amount</Th>
                </Tr>
              </Thead>
              <Tbody></Tbody>
            </Table>
          </section>
          <section>
            <StatGroup>
              <Stat>
                <StatLabel>Total Income</StatLabel>
                <StatNumber>$100</StatNumber>
              </Stat>
            </StatGroup>
          </section>
        </HStack>
      </main>
    </div>
  );
}
